version: 2

project_name: gitmanager

builds:
  - id: gitmanager
    dir: .
    main: .
    binary: gitmanager
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X danny270793/gitmanager/cmd.Version={{ .Version }}

archives:
  - id: gitmanager
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  mode: keep-existing
